---
- name: Setup Arduino Environment
  hosts: reactors
  become: yes
  gather_facts: yes
  environment:
    GH_TOKEN: your_token_here

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - unzip
      when: ansible_os_family == 'Debian'

    - name: Install Arduino CLI
      shell: >
        BINDIR=/usr/local/bin sh -c "curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh"
      environment:
        DEBIAN_FRONTEND: noninteractive
      when: ansible_os_family == 'Debian'

    - name: Update Arduino library index
      command: arduino-cli lib update-index -v
      when: ansible_os_family == 'Debian'

    - name: Download and install libraries
      get_url:
        url: "https://github.com/fotobiolab-unb/arduino-libraries/archive/v0.zip"
        dest: "/tmp/libraries.zip"
        headers:
          Authorization: "token {{ GH_TOKEN }}"
      when: ansible_os_family == 'Debian'

    - name: Extract and move libraries
      unarchive:
        src: "/tmp/libraries.zip"
        dest: "{{ lookup('env', 'HOME') }}/arduino-libraries"
      when: ansible_os_family == 'Debian'

    - name: Download source code
      get_url:
        url: "https://github.com/fotobiolab-unb/spectrum/archive/v0.zip"
        dest: "/tmp/spectrum.zip"
        headers:
          Authorization: "token {{ GH_TOKEN }}"

    - name: Extract and move source code
      unarchive:
        src: "/tmp/spectrum.zip"
        dest: "{{ lookup('env', 'HOME') }}"
      environment:
        GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"

    - name: Build image
      shell: >
        arduino-cli compile -b arduino:avr:mega $HOME/spectrum/src;
        arduino-cli upload -t -b arduino:avr:mega -p "$(arduino-cli board list | grep 'USB' | awk '{print $1}')" $HOME/spectrum/src
      environment:
        GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"
