---
- name: Setup Arduino Environment
  hosts: reactors
  become: yes
  gather_facts: yes
  environment:
      GH_TOKEN:your_token_here

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - git
        - unzip
      when: ansible_os_family == 'Debian'

    - name: Install Arduino CLI
      shell: >
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh |
        BINDIR=/usr/local/bin sh
      environment:
        DEBIAN_FRONTEND: noninteractive
      when: ansible_os_family == 'Debian'

    - name: Update Arduino library index
      command: arduino-cli lib update-index -v
      when: ansible_os_family == 'Debian'

    - name: Download and install libraries
      shell: >
        arduino_home=$(arduino-cli config dump | grep 'user:' | awk '{print $2}');
        gh release download v0 --archive=zip --repo fotobiolab-unb/arduino-libraries;
        mv arduino-libraries-0.zip libraries.zip;
        unzip libraries.zip -d $arduino_home;
        rm libraries.zip;
        mv $arduino_home/arduino-libraries-0 $arduino_home/arduino-libraries
      environment:
        GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"
      when: ansible_os_family == 'Debian'

    - name: Download source code
      shell: >
        gh release download v0 --archive=zip --repo fotobiolab-unb/spectrum;
        mv spectrum-0.zip spectrum.zip;
        unzip spectrum.zip -d $HOME;
        rm spectrum.zip;
        mv $HOME/spectrum-0 $HOME/spectrum
      environment:
        GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"

    - name: Build image
      shell: >
        arduino-cli compile -b arduino:avr:mega $HOME/spectrum/src;
        arduino-cli upload -t -b arduino:avr:mega -p "$(arduino-cli board list | grep 'USB' | awk '{print $1}')" $HOME/spectrum/src
      environment:
        GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"
